def function_code_to_coil(function_code: str) -> int:
    group = function_code[0:1]
    glt = {"F": 0, "E": 1, "C": 2, "P": 3, "H": 4, "A": 5, "b": 18, "r":10, "S": 7, "o": 6, "M": 8, "J": 13, "d": 19, "y": 14, "W": 15, "X": 16, "Z": 17}
    idn = int(function_code[1:])
    return glt[group]<<8 | idn

def alarm_lookup(alarm_code: int) -> str:
    error_codes = {
        0: 'No alarm',
        1: 'Overcurrent (during acceleration)',
        2: 'Overcurrent (during deceleration)',
        3: 'Overcurrent (during constant speed operation)',
        5: 'Ground fault',
        6: 'Overvoltage (during acceleration)',
        7: 'Overvoltage (during deceleration)',
        8: 'Overvoltage (during constant speed operation or stopping)',
        10: 'Under voltage',
        11: 'Input phase loss',
        14: 'Fuse blown',
        16: 'Charging circuit fault',
        17: 'Heat sink overheat',
        18: 'External alarm',
        19: 'Internal air overheat',
        20: 'Motor protection (PTC/NTC thermistor)',
        22: 'Braking resistor overheat',
        23: 'Motor overload',
        24: 'Motor overload: motor 2',
        25: 'Inverter overload',
        27: 'Over speed protection',
        28: 'PG disconnection',
        29: 'NTC disconnection error',
        31: 'Memory error',
        32: 'Keypad communications error',
        33: 'CPU error',
        34: 'Option communications error',
        35: 'Option error',
        36: 'Run operation error',
        37: 'Tuning error',
        38: 'RS-485 communications error (communications port1)',
        42: 'Step-out detection',
        43: 'Motor selecting error',
        44: 'Motor overload: motor 3',
        45: 'Motor overload: motor 4',
        46: 'Output phase loss',
        47: 'Following error, excessive speed deviation',
        50: 'Position of magnetic pole error',
        51: 'Data save error on insufficient voltage',
        53: 'RS-485 communications error (Option/Communications port 2)',
        54: 'Hardware error',
        55: 'CAN communications failure',
        56: 'Positioning control error',
        57: 'EN circuit error',
        58: 'PID feedback disconnection detected',
        59: 'DB transistor trouble',
        65: 'Customizable logic failure',
        66: 'PID control 1 feedback error detection',
        67: 'PID control 2 feedback error detection',
        68: 'USB port transmittion error',
        70: 'Charging resistor overheat',
        81: 'Drought protection',
        82: 'Control of maximum starts per hour',
        83: 'End of curve protection',
        84: 'Anti jam',
        85: 'Filter clogging error',
        91: 'External PID control 1 feedback error detection',
        92: 'External PID control 2 feedback error detection',
        93: 'External PID control 3 feedback error detection',
        100: 'DC fan lock detected',
        101: 'Motor overload warning',
        102: 'Cooling fin overheat warning',
        103: 'Life warning',
        104: 'Command loss',
        105: 'PID warning output',
        106: 'Low torque detected',
        107: 'Thermistor detected (PTC)',
        108: 'Machine life (accumulated operation hours)',
        109: 'Machine life (No. of starting times)',
        166: 'PID control 1 warning output',
        167: 'PID control 2 warning output',
        190: 'Mutual operation slave inverter alarm',
        191: 'External PID control 1 warning output',
        192: 'External PID control 2 warning output',
        193: 'External PID control 3 warning output',
        252: 'Forced operation',
        253: 'Password protection',
        254: 'Simulated error'
    }
    error = error_codes[alarm_code]
    return error